CATEGORIES = [
"Ask My Accountant",
"Advertising and Promotion",
"Bank Fees",
"Car and Truck Expenses",
"Charitable Contributions",
"Contract Labor",
"Subcontractor",
"Employee Benefits",
"Employee Wages",
"Equipment Rental",
"Freight and Shipping",
"Gas and Fuel and Oil",
"Insurance",
"Interest",
"Legal and Professional Services",
"Maintenance and Repairs",
"Miscellaneous",
"Office Supplies",
"Payroll Taxes",
"Rent",
"Meals and Entertainment",
"Marketing and Promotion",
"Telephone and Internet",
"Travel",
"Utilities",
"Bad Debt",
"Commissions",
"Depreciation",
"Security",
"Shareholder Distributions"]

INCOME = [
"Ask My Accountant",
"Merchant Income",
"Office Supplies",
"Income",
"Shareholder Distributions",
"Restaurant Supplies"
]
